export type FaucetCategory =
  | "aggregator"
  | "ethereum"
  | "l2"
  | "appchain"
  | "stablecoin";

export type FaucetReliability = "official" | "provider" | "community";

export interface FaucetVariant {
  chain: string;
  chainId?: number;
  token: string;
  amount: string;
}

export interface FaucetEntry {
  id: string;
  name: string;
  provider: string;
  url: string;
  faviconDomain?: string;
  chain: string;
  supportedChains?: string[];
  variants?: FaucetVariant[];
  token: string;
  amount: string;
  cooldownHours: number;
  category: FaucetCategory;
  reliability: FaucetReliability;
  requirement: string;
  notes: string;
  tags: string[];
}

export const faucetCategories: Array<{
  id: "all" | FaucetCategory;
  label: string;
}> = [
  { id: "all", label: "All" },
  { id: "ethereum", label: "Ethereum" },
  { id: "l2", label: "L2s" },
  { id: "appchain", label: "Appchains" },
  { id: "stablecoin", label: "Stablecoins" },
  { id: "aggregator", label: "Aggregators" },
];

export const faucets: FaucetEntry[] = [
  {
    id: "circle-usdc",
    name: "Testnet Faucet",
    provider: "Circle",
    url: "https://faucet.circle.com/",
    chain: "Supported testnets",
    supportedChains: [
      "Ethereum Sepolia",
      "Base Sepolia",
      "OP Sepolia",
      "Arbitrum Sepolia",
      "Polygon Amoy",
      "Avalanche Fuji",
    ],
    token: "USDC, EURC, cirBTC",
    amount: "20 USDC every 2h",
    cooldownHours: 2,
    category: "stablecoin",
    reliability: "official",
    requirement: "No account for public stablecoin faucet",
    notes: "Public faucet for Circle test assets across supported chains.",
    tags: ["stablecoin", "usdc", "eurc"],
  },
  {
    id: "google-cloud-sepolia",
    name: "Ethereum Sepolia Faucet",
    provider: "Google Cloud",
    url: "https://cloud.google.com/application/web3/faucet/ethereum/sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "Varies",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "provider",
    requirement: "Gmail login",
    notes: "Google Cloud Web3 faucet for Sepolia ETH.",
    tags: ["ethereum", "sepolia", "eth"],
  },
  {
    id: "pk910-sepolia",
    name: "Sepolia PoW Faucet",
    provider: "pk910",
    url: "https://sepolia-faucet.pk910.de/",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "0.05-2.5 ETH",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "community",
    requirement: "Browser proof-of-work",
    notes:
      "Proof-of-work faucet with a public balance and recent activity feed.",
    tags: ["ethereum", "sepolia", "pow"],
  },
  {
    id: "devcon-pk910-sepolia",
    name: "Devcon Sepolia Faucet",
    provider: "pk910",
    url: "https://devcon-sepolia-faucet.pk910.de/",
    faviconDomain: "https://sepolia-faucet.pk910.de/",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "Varies",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "community",
    requirement: "Browser proof-of-work",
    notes: "Devcon Sepolia faucet using the pk910 faucet stack.",
    tags: ["ethereum", "devcon", "sepolia"],
  },
  {
    id: "quicknode-sepolia",
    name: "Ethereum Sepolia Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/ethereum/sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "0.25-1 ETH every 12h",
    cooldownHours: 12,
    category: "ethereum",
    reliability: "provider",
    requirement: "Wallet connect; mainnet balance or social share may apply",
    notes: "Direct Ethereum Sepolia route for QuickNode's multi-chain faucet.",
    tags: ["ethereum", "sepolia", "eth"],
  },
  {
    id: "alchemy-sepolia",
    name: "Ethereum Sepolia Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/ethereum-sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "0.1 ETH every 24h",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "provider",
    requirement: "Wallet address; mainnet balance and activity checks",
    notes: "Alchemy's Sepolia faucet route; sepoliafaucet.com redirects here.",
    tags: ["ethereum", "sepolia", "eth"],
  },
  {
    id: "tatum-sepolia",
    name: "Sepolia Faucet",
    provider: "Tatum",
    url: "https://tatum.io/faucets/sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "0.002 ETH every 24h",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "provider",
    requirement: "Tatum account; 0.001 native mainnet balance",
    notes: "Direct Tatum Sepolia faucet.",
    tags: ["ethereum", "sepolia", "eth"],
  },
  {
    id: "testnet-help-sepolia",
    name: "Ethereum Sepolia Faucet",
    provider: "testnet.help",
    url: "https://testnet.help/en/ethfaucet/sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "< 0.001 ETH",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "community",
    requirement: "Captcha",
    notes: "Direct Sepolia faucet listed by FaucetLink.",
    tags: ["ethereum", "sepolia", "eth", "captcha"],
  },
  {
    id: "getblock-sepolia",
    name: "Ethereum Sepolia Faucet",
    provider: "GetBlock",
    url: "https://getblock.io/faucet/eth-sepolia/",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "0.1 ETH",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "provider",
    requirement: "GetBlock account",
    notes: "Direct GetBlock Sepolia faucet.",
    tags: ["ethereum", "sepolia", "eth"],
  },
  {
    id: "chainlink-sepolia",
    name: "Ethereum Sepolia Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH + LINK",
    amount: "0.5 ETH or 25 LINK",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Native Sepolia ETH and LINK faucet.",
    tags: ["ethereum", "sepolia", "link"],
  },
  {
    id: "chainstack-sepolia",
    name: "Sepolia Testnet Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/sepolia-testnet-faucet",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "Up to 0.5 ETH every 24h",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "provider",
    requirement: "Chainstack API key",
    notes: "Chainstack platform faucet for Sepolia.",
    tags: ["ethereum", "sepolia", "eth"],
  },
  {
    id: "chainstack-hoodi",
    name: "Hoodi Testnet Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/hoodi-testnet-faucet",
    chain: "Ethereum Hoodi",
    token: "ETH",
    amount: "Up to 0.5 ETH every 24h",
    cooldownHours: 24,
    category: "ethereum",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Hoodi testnet.",
    tags: ["ethereum", "hoodi", "eth"],
  },
  {
    id: "chainstack-bnb-testnet",
    name: "BNB Smart Chain Testnet Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/bnb-testnet-faucet",
    chain: "BNB Smart Chain Testnet",
    token: "BNB",
    amount: "Up to 0.5 BNB every 24h",
    cooldownHours: 24,
    category: "appchain",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for BNB Smart Chain testnet.",
    tags: ["bnb", "bsc", "testnet"],
  },
  {
    id: "chainstack-base-sepolia",
    name: "Base Sepolia Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/base-testnet-faucet",
    chain: "Base Sepolia",
    token: "ETH",
    amount: "Up to 0.5 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Base Sepolia.",
    tags: ["base", "sepolia", "eth"],
  },
  {
    id: "chainstack-monad",
    name: "Monad Testnet Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/monad-testnet-faucet",
    chain: "Monad Testnet",
    token: "MON",
    amount: "Up to 0.5 MON every 24h",
    cooldownHours: 24,
    category: "appchain",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Monad testnet.",
    tags: ["monad", "testnet", "mon"],
  },
  {
    id: "chainstack-polygon-amoy",
    name: "Polygon Amoy Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/amoy-faucet",
    chain: "Polygon Amoy",
    token: "POL",
    amount: "Up to 0.01 POL every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Polygon Amoy.",
    tags: ["polygon", "amoy", "pol"],
  },
  {
    id: "chainstack-plasma",
    name: "Plasma Testnet Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/plasma-testnet-faucet",
    chain: "Plasma Testnet",
    token: "XPL",
    amount: "Up to 0.05 XPL every 24h",
    cooldownHours: 24,
    category: "appchain",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Plasma testnet.",
    tags: ["plasma", "testnet", "xpl"],
  },
  {
    id: "chainstack-hyperliquid",
    name: "Hyperliquid Testnet Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/hyperliquid-testnet-faucet",
    chain: "HyperEVM Testnet",
    token: "HYPE",
    amount: "Up to 1 HYPE every 24h",
    cooldownHours: 24,
    category: "appchain",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Hyperliquid testnet HYPE.",
    tags: ["hyperevm", "hyperliquid", "testnet", "hype"],
  },
  {
    id: "chainstack-zksync-sepolia",
    name: "ZKsync Sepolia Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/zksync-testnet-faucet",
    chain: "ZKsync Sepolia",
    token: "ETH",
    amount: "Up to 0.05 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for ZKsync Sepolia.",
    tags: ["zksync", "sepolia", "eth"],
  },
  {
    id: "chainstack-scroll-sepolia",
    name: "Scroll Sepolia Faucet",
    provider: "Chainstack",
    url: "https://faucet.chainstack.com/scroll-sepolia-testnet-faucet",
    chain: "Scroll Sepolia",
    token: "ETH",
    amount: "Up to 0.5 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Chainstack API key; mainnet ETH balance/history checks",
    notes: "Chainstack platform faucet for Scroll Sepolia.",
    tags: ["scroll", "sepolia", "eth"],
  },
  {
    id: "gaszip-sepolia",
    name: "Sepolia Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/sepolia",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "0.003-0.125 ETH",
    cooldownHours: 12,
    category: "ethereum",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Sepolia faucet route.",
    tags: ["gaszip", "ethereum", "sepolia", "eth"],
  },
  {
    id: "gaszip-robinhood",
    name: "Robinhood Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/robinhood",
    chain: "Robinhood Testnet",
    token: "ETH",
    amount: "0.003-0.125 ETH",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Robinhood Testnet faucet route.",
    tags: ["gaszip", "robinhood", "testnet", "eth"],
  },
  {
    id: "gaszip-rise",
    name: "RISE Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/rise",
    chain: "RISE Testnet",
    token: "ETH",
    amount: "0.003-0.125 ETH",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct RISE Testnet faucet route.",
    tags: ["gaszip", "rise", "testnet", "eth"],
  },
  {
    id: "gaszip-polygon-amoy",
    name: "Polygon Amoy Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/polygon",
    chain: "Polygon Amoy",
    token: "POL",
    amount: "0.003-0.125 POL",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Polygon Amoy faucet route.",
    tags: ["gaszip", "polygon", "amoy", "pol"],
  },
  {
    id: "gaszip-op-sepolia",
    name: "Optimism Sepolia Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/optimism",
    chain: "OP Sepolia",
    token: "ETH",
    amount: "0.003-0.125 ETH",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Optimism Sepolia faucet route.",
    tags: ["gaszip", "optimism", "op", "sepolia", "eth"],
  },
  {
    id: "gaszip-megaeth",
    name: "MegaETH Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/megaeth",
    chain: "MegaETH Testnet",
    token: "ETH",
    amount: "0.002-0.222 ETH",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct MegaETH Testnet faucet route.",
    tags: ["gaszip", "megaeth", "testnet", "eth"],
  },
  {
    id: "gaszip-hyperevm",
    name: "HyperEVM Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/hyperevm",
    chain: "HyperEVM Testnet",
    token: "HYPE",
    amount: "0.125-2.222 HYPE",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct HyperEVM Testnet faucet route.",
    tags: ["gaszip", "hyperevm", "hyperliquid", "testnet", "hype"],
  },
  {
    id: "gaszip-bnb-testnet",
    name: "BSC Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/bsc",
    chain: "BNB Smart Chain Testnet",
    token: "BNB",
    amount: "0.045-0.999 BNB",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct BSC Testnet faucet route.",
    tags: ["gaszip", "bnb", "bsc", "testnet"],
  },
  {
    id: "gaszip-base-sepolia",
    name: "Base Sepolia Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/base",
    chain: "Base Sepolia",
    token: "ETH",
    amount: "0.003-0.125 ETH",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Base Sepolia faucet route.",
    tags: ["gaszip", "base", "sepolia", "eth"],
  },
  {
    id: "gaszip-avalanche-fuji",
    name: "Avalanche Testnet Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/avax",
    chain: "Avalanche Fuji",
    token: "AVAX",
    amount: "0.045-0.999 AVAX",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Avalanche testnet faucet route.",
    tags: ["gaszip", "avalanche", "fuji", "avax"],
  },
  {
    id: "gaszip-arbitrum-sepolia",
    name: "Arbitrum Sepolia Faucet",
    provider: "Gas.zip",
    url: "https://www.gas.zip/faucet/arbitrum",
    chain: "Arbitrum Sepolia",
    token: "ETH",
    amount: "0.003-0.125 ETH",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect; mainnet or Gas.zip activity eligibility",
    notes: "Gas.zip direct Arbitrum Sepolia faucet route.",
    tags: ["gaszip", "arbitrum", "sepolia", "eth"],
  },
  {
    id: "ethglobal-faucet",
    name: "ETHGlobal Faucet",
    provider: "ETHGlobal",
    url: "https://ethglobal.com/faucet",
    chain: "Supported testnets",
    variants: [
      {
        chain: "Ethereum Sepolia",
        chainId: 11155111,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Ethereum Sepolia",
        chainId: 11155111,
        token: "USDC",
        amount: "1 USDC",
      },
      {
        chain: "OP Sepolia",
        chainId: 11155420,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Base Sepolia",
        chainId: 84532,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Arbitrum Sepolia",
        chainId: 421614,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "ZKsync Sepolia",
        chainId: 300,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Polygon Amoy",
        chainId: 80002,
        token: "POL",
        amount: "0.05 POL",
      },
      {
        chain: "Scroll Sepolia",
        chainId: 534351,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Filecoin Calibration",
        chainId: 314159,
        token: "FIL",
        amount: "0.05 FIL",
      },
      {
        chain: "Gnosis Chiado Testnet",
        chainId: 10200,
        token: "XDAI",
        amount: "0.05 XDAI",
      },
      {
        chain: "ApeChain Testnet",
        chainId: 33111,
        token: "APE",
        amount: "0.05 APE",
      },
      {
        chain: "WorldChain Sepolia",
        chainId: 4801,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Unichain Sepolia",
        chainId: 1301,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Zircuit Garfield Testnet",
        chainId: 48898,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Citrea Testnet",
        chainId: 5115,
        token: "CBTC",
        amount: "0.005 CBTC",
      },
      {
        chain: "Flow EVM Testnet",
        chainId: 545,
        token: "FLOW",
        amount: "0.05 FLOW",
      },
      {
        chain: "Celo Sepolia",
        chainId: 11142220,
        token: "CELO",
        amount: "0.05 CELO",
      },
      {
        chain: "Ethereum Holesky",
        chainId: 17000,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Polygon Mumbai",
        chainId: 80001,
        token: "MATIC",
        amount: "0.05 MATIC",
      },
      {
        chain: "Zircuit Testnet",
        chainId: 48899,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Story Partner Testnet",
        chainId: 1513,
        token: "IP",
        amount: "0.05 IP",
      },
      {
        chain: "Linea Sepolia",
        chainId: 59141,
        token: "ETH",
        amount: "0.05 ETH",
      },
      {
        chain: "Monad Testnet",
        chainId: 10143,
        token: "MON",
        amount: "0.2 MON",
      },
    ],
    token: "ETH, USDC, POL, FIL, XDAI, APE, CBTC, FLOW, CELO, MATIC, IP, MON",
    amount: "Varies by network",
    cooldownHours: 24,
    category: "appchain",
    reliability: "official",
    requirement: "Email login",
    notes: "ETHGlobal faucet with per-network testnet allocations.",
    tags: [
      "ethereum",
      "sepolia",
      "base",
      "optimism",
      "arbitrum",
      "polygon",
      "monad",
      "zircuit",
      "scroll",
      "linea",
      "worldchain",
      "filecoin",
      "gnosis",
      "apechain",
      "flow",
      "celo",
      "citrea",
    ],
  },
  {
    id: "sepoliaeth-buy",
    name: "Buy Sepolia ETH",
    provider: "SepoliaETH.com",
    url: "https://www.sepoliaeth.com/buy-sepolia-eth",
    chain: "Ethereum Sepolia",
    token: "ETH",
    amount: "Paid backup",
    cooldownHours: 1,
    category: "ethereum",
    reliability: "community",
    requirement: "Payment",
    notes: "Not a free faucet; included as a last-resort Sepolia source.",
    tags: ["ethereum", "sepolia", "paid"],
  },
  {
    id: "cdp-base-sepolia",
    name: "CDP Faucet",
    provider: "Coinbase Developer Platform",
    url: "https://portal.cdp.coinbase.com/products/faucet",
    faviconDomain: "coinbase.com",
    chain: "Base Sepolia",
    token: "ETH, USDC, EURC, cbBTC",
    amount: "Up to 0.1 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "Coinbase account login",
    notes: "Official Base docs list CDP for Base Sepolia testnet assets.",
    tags: ["base", "sepolia", "coinbase"],
  },
  {
    id: "thirdweb-base-sepolia",
    name: "Base Sepolia Faucet",
    provider: "thirdweb",
    url: "https://thirdweb.com/base-sepolia-testnet",
    chain: "Base Sepolia",
    token: "ETH",
    amount: "One claim every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "thirdweb account",
    notes: "Base docs list thirdweb as a Base Sepolia faucet.",
    tags: ["base", "sepolia", "eth"],
  },
  {
    id: "alchemy-base-sepolia",
    name: "Base Sepolia Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/base-sepolia",
    chain: "Base Sepolia",
    token: "ETH",
    amount: "0.1 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Free Alchemy account",
    notes: "Alchemy's Base Sepolia faucet route.",
    tags: ["base", "sepolia", "eth"],
  },
  {
    id: "quicknode-base-sepolia",
    name: "Base Sepolia Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/base/sepolia",
    chain: "Base Sepolia",
    token: "ETH",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode Base Sepolia route.",
    tags: ["base", "sepolia", "eth"],
  },
  {
    id: "chainlink-base-sepolia",
    name: "Base Sepolia Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/base-sepolia",
    chain: "Base Sepolia",
    token: "ETH + LINK",
    amount: "0.5 ETH or 25 LINK",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Native Base Sepolia ETH and LINK faucet.",
    tags: ["base", "sepolia", "link"],
  },
  {
    id: "ethfaucet-base",
    name: "Base ETH Faucet",
    provider: "ethfaucet.com",
    url: "https://ethfaucet.com/",
    chain: "Base Sepolia",
    token: "ETH",
    amount: "Varies",
    cooldownHours: 24,
    category: "l2",
    reliability: "community",
    requirement: "Wallet address",
    notes: "Provides Base Sepolia test ETH.",
    tags: ["base", "sepolia"],
  },
  {
    id: "optimism-console",
    name: "Superchain Faucet",
    provider: "Optimism",
    url: "https://console.optimism.io/faucet",
    chain: "Supported testnets",
    supportedChains: [
      "OP Sepolia",
      "Base Sepolia",
      "Unichain Sepolia",
      "Ink Sepolia",
      "WorldChain Sepolia",
      "Ethereum Sepolia",
    ],
    token: "ETH",
    amount: "Varies",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "Wallet connect",
    notes:
      "Optimism developer console faucet for OP, Base, Unichain, Ink, WorldChain, and Ethereum Sepolia.",
    tags: [
      "optimism",
      "op",
      "base",
      "unichain",
      "ink",
      "worldchain",
      "ethereum",
    ],
  },
  {
    id: "quicknode-op-sepolia",
    name: "Optimism Sepolia Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/optimism/sepolia",
    chain: "OP Sepolia",
    token: "ETH",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode OP Sepolia route.",
    tags: ["optimism", "sepolia", "eth"],
  },
  {
    id: "alchemy-op-sepolia",
    name: "Optimism Sepolia Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/optimism-sepolia",
    chain: "OP Sepolia",
    token: "ETH",
    amount: "0.1 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet address; reputation checks may apply",
    notes: "Alchemy's OP Sepolia faucet route.",
    tags: ["optimism", "sepolia", "eth"],
  },
  {
    id: "chainlink-op-sepolia",
    name: "OP Sepolia Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/optimism-sepolia",
    chain: "OP Sepolia",
    token: "ETH + LINK",
    amount: "Varies",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Chainlink OP Sepolia faucet.",
    tags: ["optimism", "sepolia", "link"],
  },
  {
    id: "quicknode-arb-sepolia",
    name: "Arbitrum Sepolia Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/arbitrum/sepolia",
    chain: "Arbitrum Sepolia",
    token: "ETH",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode Arbitrum Sepolia route.",
    tags: ["arbitrum", "sepolia", "eth"],
  },
  {
    id: "alchemy-arb-sepolia",
    name: "Arbitrum Sepolia Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/arbitrum-sepolia",
    chain: "Arbitrum Sepolia",
    token: "ETH",
    amount: "0.1 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet address; reputation checks may apply",
    notes: "Alchemy's Arbitrum Sepolia faucet route.",
    tags: ["arbitrum", "sepolia", "eth"],
  },
  {
    id: "chainlink-arb-sepolia",
    name: "Arbitrum Sepolia Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/arbitrum-sepolia",
    chain: "Arbitrum Sepolia",
    token: "ETH + LINK",
    amount: "0.5 ETH or 25 LINK",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Native Arbitrum Sepolia ETH and LINK faucet.",
    tags: ["arbitrum", "sepolia", "link"],
  },
  {
    id: "quicknode-unichain-sepolia",
    name: "Unichain Sepolia Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/unichain/sepolia",
    chain: "Unichain Sepolia",
    token: "ETH",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode Unichain Sepolia route.",
    tags: ["unichain", "sepolia", "eth"],
  },
  {
    id: "thirdweb-unichain-sepolia",
    name: "Unichain Sepolia Testnet",
    provider: "thirdweb",
    url: "https://thirdweb.com/unichain-sepolia-testnet",
    chain: "Unichain Sepolia",
    token: "ETH",
    amount: "Varies",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "thirdweb account",
    notes:
      "thirdweb network page with wallet actions and faucet access where available.",
    tags: ["unichain", "sepolia", "eth"],
  },
  {
    id: "chainlink-unichain",
    name: "Unichain Sepolia Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/unichain-testnet",
    chain: "Unichain Sepolia",
    token: "ETH + LINK",
    amount: "Varies",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Chainlink Unichain Sepolia ETH and LINK faucet.",
    tags: ["unichain", "link", "eth"],
  },
  {
    id: "polygon-amoy",
    name: "Polygon Faucet",
    provider: "Polygon",
    url: "https://faucet.polygon.technology/",
    chain: "Polygon Amoy",
    token: "POL",
    amount: "Varies",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "Wallet address",
    notes:
      "Polygon docs now point developers to third-party faucets too, so keep backups nearby.",
    tags: ["polygon", "amoy", "pol"],
  },
  {
    id: "quicknode-polygon-amoy",
    name: "Polygon Amoy Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/polygon/amoy",
    chain: "Polygon Amoy",
    token: "POL",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode Polygon Amoy route.",
    tags: ["polygon", "amoy", "pol"],
  },
  {
    id: "alchemy-polygon-amoy",
    name: "Polygon Amoy Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/polygon-amoy",
    chain: "Polygon Amoy",
    token: "POL",
    amount: "0.1 POL every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet address; reputation checks may apply",
    notes: "Alchemy's Polygon Amoy faucet route.",
    tags: ["polygon", "amoy", "pol"],
  },
  {
    id: "chainlink-polygon-amoy",
    name: "Polygon Amoy Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/polygon-amoy",
    chain: "Polygon Amoy",
    token: "POL + LINK",
    amount: "0.5 POL or 25 LINK",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Native Polygon Amoy POL and LINK faucet.",
    tags: ["polygon", "amoy", "link"],
  },
  {
    id: "core-avalanche-fuji",
    name: "Testnet Faucet",
    provider: "Core Wallet",
    url: "https://core.app/tools/testnet-faucet",
    chain: "Avalanche Fuji",
    token: "AVAX",
    amount: "Varies",
    cooldownHours: 24,
    category: "appchain",
    reliability: "official",
    requirement: "Wallet address",
    notes: "Avalanche Fuji faucet through Core.",
    tags: ["avalanche", "fuji", "avax"],
  },
  {
    id: "quicknode-avalanche-fuji",
    name: "Avalanche Fuji Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/avalanche/fuji",
    chain: "Avalanche Fuji",
    token: "AVAX",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode Avalanche Fuji route.",
    tags: ["avalanche", "fuji", "avax"],
  },
  {
    id: "chainlink-avalanche-fuji",
    name: "Avalanche Fuji Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/fuji",
    chain: "Avalanche Fuji",
    token: "AVAX + LINK",
    amount: "0.5 AVAX or 25 LINK",
    cooldownHours: 24,
    category: "appchain",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Native Avalanche Fuji AVAX and LINK faucet.",
    tags: ["avalanche", "fuji", "link"],
  },
  {
    id: "bnb-official",
    name: "BNB Testnet Faucet",
    provider: "BNB Chain",
    url: "https://www.bnbchain.org/en/testnet-faucet",
    chain: "BNB Smart Chain Testnet",
    token: "BNB",
    amount: "0.3 BNB every 24h",
    cooldownHours: 24,
    category: "appchain",
    reliability: "official",
    requirement: "0.002 BNB on mainnet",
    notes: "Official BNB Chain faucet.",
    tags: ["bnb", "testnet", "bsc"],
  },
  {
    id: "quicknode-bnb-testnet",
    name: "BNB Chain Testnet Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/binance-smart-chain/testnet",
    chain: "BNB Smart Chain Testnet",
    token: "BNB",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode BNB Chain testnet route.",
    tags: ["bnb", "testnet", "bsc"],
  },
  {
    id: "quicknode-zksync-sepolia",
    name: "ZKsync Sepolia Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/zksync/sepolia",
    chain: "ZKsync Sepolia",
    token: "ETH",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode ZKsync Sepolia route.",
    tags: ["zksync", "sepolia", "eth"],
  },
  {
    id: "alchemy-zksync-sepolia",
    name: "ZKsync Sepolia Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/zksync-sepolia",
    chain: "ZKsync Sepolia",
    token: "ETH",
    amount: "0.1 ETH every 24h",
    cooldownHours: 24,
    category: "l2",
    reliability: "provider",
    requirement: "Wallet address; reputation checks may apply",
    notes: "Alchemy's ZKsync Sepolia faucet route.",
    tags: ["zksync", "sepolia", "eth"],
  },
  {
    id: "chainlink-zksync-sepolia",
    name: "ZKsync Sepolia Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/zksync-sepolia",
    chain: "ZKsync Sepolia",
    token: "ETH + LINK",
    amount: "0.5 ETH or 25 LINK",
    cooldownHours: 24,
    category: "l2",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Native ZKsync Sepolia ETH and LINK faucet.",
    tags: ["zksync", "sepolia", "link"],
  },
  {
    id: "alchemy-monad",
    name: "Monad Testnet Faucet",
    provider: "Alchemy",
    url: "https://www.alchemy.com/faucets/monad-testnet",
    chain: "Monad Testnet",
    token: "MON",
    amount: "1 MON every 24h",
    cooldownHours: 24,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet address; reputation checks may apply",
    notes: "Alchemy's Monad testnet faucet route.",
    tags: ["monad", "testnet", "mon"],
  },
  {
    id: "quicknode-monad",
    name: "Monad Testnet Faucet",
    provider: "QuickNode",
    url: "https://faucet.quicknode.com/monad/testnet",
    chain: "Monad Testnet",
    token: "MON",
    amount: "One drip every 12h",
    cooldownHours: 12,
    category: "appchain",
    reliability: "provider",
    requirement: "Wallet connect",
    notes: "QuickNode Monad testnet route.",
    tags: ["monad", "testnet", "mon"],
  },
  {
    id: "chainlink-monad",
    name: "Monad Testnet Faucet",
    provider: "Chainlink",
    url: "https://faucets.chain.link/monad-testnet",
    chain: "Monad Testnet",
    token: "MON + LINK",
    amount: "Varies",
    cooldownHours: 24,
    category: "appchain",
    reliability: "official",
    requirement: "1 LINK on Ethereum mainnet in the claiming address",
    notes: "Chainlink Monad testnet MON and LINK faucet.",
    tags: ["monad", "testnet", "link"],
  },
];
