import fs from "node:fs";
import path from "node:path";
import solc from "solc";

const ROOT = process.cwd();
const CONTRACT_DIR = path.join(ROOT, "contracts/robin-bridge");
const OUTPUT_FILE = path.join(
  ROOT,
  "app/robin-bridge/lib/oftArtifacts.generated.ts"
);
const STANDARD_INPUT_FILE = path.join(
  ROOT,
  "app/robin-bridge/lib/oftStandardInput.generated.json"
);

const sources: Record<string, { content: string }> = {};

function collectSource(sourceName: string, filePath: string) {
  if (sources[sourceName]) return;
  const content = fs.readFileSync(filePath, "utf8");
  sources[sourceName] = { content };
  const imports = content.matchAll(
    /import\s+(?:[^"']+from\s+)?["']([^"']+)["'];/g
  );
  for (const match of imports) {
    const importPath = match[1];
    const importedSourceName = importPath.startsWith(".")
      ? path.posix.normalize(
          path.posix.join(path.posix.dirname(sourceName), importPath)
        )
      : importPath;
    const importedFilePath = importPath.startsWith(".")
      ? path.resolve(path.dirname(filePath), importPath)
      : path.join(ROOT, "node_modules", importPath);
    collectSource(importedSourceName, importedFilePath);
  }
}

collectSource(
  "RobinOFTAdapter.sol",
  path.join(CONTRACT_DIR, "RobinOFTAdapter.sol")
);
collectSource("RobinOFT.sol", path.join(CONTRACT_DIR, "RobinOFT.sol"));

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "paris",
    outputSelection: {
      "*": {
        "*": ["evm.bytecode.object"],
      },
    },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []).filter(
  (entry: { severity: string }) => entry.severity === "error"
);
if (errors.length) {
  throw new Error(
    errors
      .map((entry: { formattedMessage: string }) => entry.formattedMessage)
      .join("\n")
  );
}

const adapterBytecode =
  output.contracts["RobinOFTAdapter.sol"].RobinOFTAdapter.evm.bytecode.object;
const oftBytecode =
  output.contracts["RobinOFT.sol"].RobinOFT.evm.bytecode.object;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(
  OUTPUT_FILE,
  `// Generated by scripts/buildRobinOftArtifacts.ts. Do not edit manually.\n` +
    `export const ROBIN_OFT_ADAPTER_BYTECODE = "0x${adapterBytecode}" as const;\n` +
    `export const ROBIN_OFT_BYTECODE = "0x${oftBytecode}" as const;\n`
);
fs.writeFileSync(STANDARD_INPUT_FILE, `${JSON.stringify(input)}\n`);

console.log(`Wrote ${path.relative(ROOT, OUTPUT_FILE)}`);
console.log(`Wrote ${path.relative(ROOT, STANDARD_INPUT_FILE)}`);
